apiVersion: apps/v1
kind: Deployment
metadata:
  name: fail2ban
  labels:
    app: fail2ban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fail2ban
  template:
    metadata:
      labels:
        app: fail2ban
    spec:
      containers:
        - image: fail2ban:1.0.0
          imagePullPolicy: Never
          name: fail2ban
      restartPolicy: Always
      serviceAccount: fail2ban
      serviceAccountName: fail2ban

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fail2ban

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fail2ban
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - list
      - get
      - create
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fail2ban
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fail2ban
subjects:
  - kind: ServiceAccount
    name: fail2ban
    namespace: vpn
